[package]
name = "taylors-version"
version = "0.1.0"
authors = ["Bentley Hensel <github@bentleyhensel.com>"]
edition = "2018"

[dependencies]
rocket = { version = "=0.5.0-rc.3", features = ["secrets"] }


dotenv = "0.15.0"
reqwest = "0.11.20"




